# Generated by Django 3.1.3 on 2022-11-03 01:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0005_matricula_fechamatricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Academica.curso'),
            preserve_default=False,
        ),
    ]
